
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-green
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
      version: green
  template:
    metadata:
      labels:
        app: messaging-app
        version: green
    spec:
      containers:
      - name: messaging-app
        image: your_dockerhub_username/messaging-app:v2
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "messaging_app.settings"
