# Generated by Django 5.2.4 on 2025-07-31 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(help_text='the message that triggered this notification', on_delete=django.db.models.deletion.CASCADE, to='messaging.message'),
        ),
    ]
