version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: messaging_user
      MYSQL_DB: messaging_db
      MYSQL_PASSWORD: messaging_pass
    volumes:
      - mysql_data:/var/lib/mysql   # <--- Added volume here for data persistence
    ports:
      - "3306:3306"

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MYSQL_USER: messaging_user
      MYSQL_DB: messaging_db
      MYSQL_PASSWORD: messaging_pass
      MYSQL_HOST: db
    depends_on:
      - db

volumes:
  mysql_data:    # <--- Named volume definition
