# Generated by Django 5.2.4 on 2025-08-01 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversation', '0001_initial'),
        ('messaging', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants_id',
            field=models.ManyToManyField(related_name='participants', to='user.user'),
        ),
    ]
